### ISSUE TITLE
Showing 0 tests

### ISSUE THREAD

**Issue by hardevine** [vivait/phpspec-phpstorm-file-watcher#2]
Its showing 0 tests but when i run in Phpstorm console it works fine..

**Comment by MacDada** [comment]
Try a failing spec – the output window should appear.

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that PHPSpec is no longer part of our core tooling and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
