### ISSUE TITLE
Exception: "not valid Win32 application"

### ISSUE THREAD

**Issue by josecelano** [vivait/phpspec-phpstorm-file-watcher#4]
`An exception occurred while executing watcher 'Run PHPSpec tests'. Watcher has been disabled. Fix it.: Cannot run program "D:\GIT\Projects\MyProject\bin\phpspec" (in directory "D:\GIT\Projects\MyProject\src\myproject"): CreateProcess error=193, %1 is not a valid Win32 application`

The problem is fixed calling `phpsepc.bat` instead of `phpspec`:

```
<option name="program" value="$ProjectFileDir$/bin/phpspec.bat" />
```

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that PHPSpec is no longer part of our core tooling and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
