### ISSUE TITLE
Output in Terminal tab is prettier than Run tab

### ISSUE THREAD

**Issue by josecelano** [vivait/phpspec-phpstorm-file-watcher#5]
If I run `phpspec run` command on embedded Terminal  tab in PHPStorm I can see green/red bars (plugin for Windows) but the file watcher opens a Run tab (to show program output) and I can not see the bars there.

Is there a way to run the command as terminal command? I would like to run  `phpspec run` when I save the files as I do manually in the terminal tab.

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that PHPSpec is no longer part of our core tooling and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
