### ISSUE TITLE
$ProjectFileDir$ doesn't work

### ISSUE THREAD

**Issue by MacDada** [vivait/phpspec-phpstorm-file-watcher#6]
PhpStorm 2016.3.2, macOS 10.12.1

I had to manually point to the phpspec file in the settings window. 

![screenshot](https://dl.dropboxusercontent.com/u/3729832/published/github/vivait__phpspec-phpstorm-file-watcher.png)

**Comment by kieljohn** [comment]
Hey, thanks for the report. I'm afraid that PHPSpec is no longer part of our core tooling and we no longer use it internally. Sorry for the delay in the reply, we're in the process of clearing up our Issues and projects. I'm afraid I will be closing this, but feel free to fork the project!
